modLoader="javafml"
loaderVersion="[35,)"
license="LGPLv3"
issueTrackerURL="https://github.com/GoryMoon/GlobalGameRules/issues"

[[mods]]
modId="globalgamerules"
version="${file.jarVersion}"
displayName="Global GameRules"
credits="An idea suggested by Sevadus"
authors="Gory_Moon"
description='''
A mod that allows for global gamerules when a world is loaded
'''

[[dependencies.globalgamerules]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.globalgamerules]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
